; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
#define GTKPATH "C:\msys64\mingw64\"
#define SITE "https://slovesnov.rf.gd"
#define APPNAME "graph"
#define VERSION "1.2.9"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{A3A78A11-A8D9-4DC0-A8D3-19FEB424D97E}
;version number appears three times AppName shows application name in installer
AppName={#APPNAME}
AppVersion={#VERSION}
AppPublisher=Alexey Slovesnov
AppPublisherURL={#SITE}?{#APPNAME}
AppSupportURL={#SITE}?{#APPNAME}
AppUpdatesURL={#SITE}?{#APPNAME}
DefaultDirName={commonpf}\{#APPNAME}
;user can select setup folder
DisableDirPage=no
DefaultGroupName={#APPNAME}
OutputBaseFilename={#APPNAME}{#VERSION}Setup
SetupIconFile={#APPNAME}\icon\app.ico
Compression=lzma
SolidCompression=yes
ChangesAssociations=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "russian"; MessagesFile: "compiler:Languages\Russian.isl"

[Messages]
english.BeveledLabel=English
russian.BeveledLabel=Russian

[Files]
#define i

#dim Icons[3]
#define Icons[0] "pan-up-symbolic"
#define Icons[1] "pan-down-symbolic"
#define Icons[2] "pan-end-symbolic"

#sub IconEntry
Source: "{#GTKPATH}share\icons\Adwaita\symbolic\ui\{#Icons[i]}.svg"; DestDir: "{app}\share\icons\Adwaita\symbolic\ui"; Flags: ignoreversion
#endsub
#for {i = 0; i < DimOf(Icons); i++} IconEntry

#dim Files[45]
#define Files[0] "libLerc"
#define Files[1] "libatk-1.0-0"
#define Files[2] "libbrotlicommon"
#define Files[3] "libbrotlidec"
#define Files[4] "libbz2-1"
#define Files[5] "libcairo-2"
#define Files[6] "libcairo-gobject-2"
#define Files[7] "libdatrie-1"
#define Files[8] "libdeflate"
#define Files[9] "libepoxy-0"
#define Files[10] "libexpat-1"
#define Files[11] "libffi-8"
#define Files[12] "libfontconfig-1"
#define Files[13] "libfreetype-6"
#define Files[14] "libfribidi-0"
#define Files[15] "libgcc_s_seh-1"
#define Files[16] "libgdk-3-0"
#define Files[17] "libgdk_pixbuf-2.0-0"
#define Files[18] "libgio-2.0-0"
#define Files[19] "libglib-2.0-0"
#define Files[20] "libgmodule-2.0-0"
#define Files[21] "libgobject-2.0-0"
#define Files[22] "libgraphite2"
#define Files[23] "libgtk-3-0"
#define Files[24] "libharfbuzz-0"
#define Files[25] "libiconv-2"
#define Files[26] "libintl-8"
#define Files[27] "libjbig-0"
#define Files[28] "libjpeg-8"
#define Files[29] "liblzma-5"
#define Files[30] "libpango-1.0-0"
#define Files[31] "libpangocairo-1.0-0"
#define Files[32] "libpangoft2-1.0-0"
#define Files[33] "libpangowin32-1.0-0"
#define Files[34] "libpcre2-8-0"
#define Files[35] "libpixman-1-0"
#define Files[36] "libpng16-16"
#define Files[37] "libsharpyuv-0"
#define Files[38] "libstdc++-6"
#define Files[39] "libthai-0"
#define Files[40] "libtiff-6"
#define Files[41] "libwebp-7"
#define Files[42] "libwinpthread-1"
#define Files[43] "libzstd"
#define Files[44] "zlib1"

#sub FilesEntry
Source: "{#GTKPATH}bin\{#Files[i]}.dll"; DestDir: "{app}\bin"; Flags: ignoreversion
#endsub
#for {i = 0; i < DimOf(Files); i++} FilesEntry

Source: "{#GTKPATH}lib\gdk-pixbuf-2.0\2.10.0\loaders.cache"; DestDir: "{app}\lib\gdk-pixbuf-2.0\2.10.0"; Flags: ignoreversion
Source: "{#GTKPATH}lib\gdk-pixbuf-2.0\2.10.0\loaders\*.dll"; DestDir: "{app}\lib\gdk-pixbuf-2.0\2.10.0\loaders"; Flags: ignoreversion
Source: "{#GTKPATH}share\glib-2.0\schemas\gschemas.compiled"; DestDir: "{app}\share\glib-2.0\schemas"; Flags: ignoreversion

Source: "{#APPNAME}.exe"; DestDir: "{app}\bin"; Flags: ignoreversion
Source: "*.css"; DestDir: "{app}\bin"; Flags: ignoreversion
Source: "{#APPNAME}\images\*"; Excludes: "*.txt"; DestDir: "{app}\bin\{#APPNAME}\images"; Flags: onlyifdoesntexist

[Icons]
Name: "{group}\{#APPNAME}"; Filename: "{app}\bin\{#APPNAME}.exe"
Name: "{commondesktop}\{#APPNAME}"; Filename: "{app}\bin\{#APPNAME}.exe"
Name: "{group}\{cm:UninstallProgram,{#APPNAME}}"; Filename: "{uninstallexe}"

[Run]
Filename: "{app}\bin\{#APPNAME}.exe"; Description: "{cm:LaunchProgram,{#APPNAME}}"; Flags: nowait postinstall skipifsilent
